### ISSUE TITLE
Language switcher

### ISSUE THREAD

**Issue by pickfire** [RustMagazine/rustmagazine.github.io#3]
I saw there is chinese content in the blog, but I can't find anything to switch between english and chinese, maybe it would be nice to have something to be able to switch to chinese?

My chinese technical terms are bad, so if there is a way to easily switch between them then once in a while I can switch to chinese and read it to learn those technical terms in chinese.

**Comment by Folyd** [comment]
Hi, you can switch to a different language via this menu.

<img width="990" alt="image" src="https://user-images.githubusercontent.com/3369694/208658432-1b890194-4e2f-422d-ae44-19a03dca5d7f.png">
